# Generated by Django 4.2.16 on 2024-12-01 05:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("todoapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todo",
            old_name="completed",
            new_name="is_completed",
        ),
        migrations.RemoveField(
            model_name="todo",
            name="description",
        ),
        migrations.AddField(
            model_name="todo",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="todo",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
