# Generated by Django 4.2.16 on 2025-01-02 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todoapp", "0006_contactform_alter_blogpost_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactform",
            name="service",
            field=models.CharField(
                choices=[
                    ("private_lessons", "Private Lessons"),
                    ("group_lessons", "Group Lessons"),
                    ("skating_camps", "Skating Camps"),
                    ("cad_modeling", "CAD Modeling"),
                    ("miscellaneous", "Miscellaneous"),
                ],
                max_length=100,
            ),
        ),
    ]
