# Generated by Django 4.2.16 on 2025-01-02 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todoapp", "0007_alter_contactform_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactform",
            name="service",
            field=models.CharField(
                choices=[
                    ("data_explore", "Data Exploration"),
                    ("analytics_viz", "Analytics and Visualization"),
                    ("aiml_prediction", "Prediction and Forecasting"),
                    ("cad_modeling", "CAD Modeling"),
                    ("miscellaneous", "Miscellaneous"),
                ],
                max_length=100,
            ),
        ),
    ]
